added more lines of code -- WIP

diff --git a/squashlinux-pull b/squashlinux-pull
--- a/squashlinux-pull
+++ b/squashlinux-pull
@@ -1,8 +1,11 @@
 ## This program is a part of a bigger project
 ## https://github.com/herzeleid02/squashlinux
-# some of the code was stolen from distrobox-create :)
+## some of the code was stolen from distrobox-create :)
 
 #!/bin/bash -x # i think u can run this in any posix compatible shell
+set -o posix #kek
+# this script should run as root because of the perms 
+
 
 version="0.1"
 verbose=0
@@ -10,10 +13,82 @@ verbose_key=""
 dryrun=0 ##why
 container_image=""
 tmp_dir="/tmp/tar-$(date +%d%m%Y)-$(tr -dc a-z </dev/urandom | head -c 4)" # actually not neccessary
-flush=0 # it should not remove any already pulled images
+flush=1 # it should not remove any already pulled images
 chroot_directory=""
+rootless=0
 
-# parsing args
+function main(){
+	parse_args "$@"
+	echo ${container_image} # debug
+	echo ${chroot_directory} # debug
+	check_args # actually i should merge them (maybe)
+	init_verbose
+	podman_main
+}
+
+function parse_args(){
+	while :; do
+		case $1 in
+			-h | --help)
+				# Call a "show_help" function to display a synopsis, then exit.
+				show_help
+				exit 0
+				;;
+			-v | --verbose)
+				verbose=1
+				#verbose_key="s
+				shift
+				;;
+			-V | --version)
+				printf "Version: %s\n" "${version}" # to be changed # TODO: change it
+				exit 0
+				;;
+			-i | --image)
+				if [ -n "$2" ]; then
+					container_image="$2"
+					shift
+					shift
+				fi
+				;;
+			-F | --flush) # function to then remove the image from the host (default behaivour)
+				flush=1
+				shift
+				;;
+			--no-flush) ## disable image flushing
+				flush=0
+				shift
+				;;
+			-t | --target-directory)
+				if [ -n "$2" ]; then
+					chroot_directory="$2"
+					shift
+					shift
+				fi
+				;;
+			--rootless) ## function to create rootless bootstraps (pls dont)
+				rootless=1
+				;;
+			--) # End of all options.
+				shift
+				break
+				;;
+			-*) # Invalid options.
+				printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
+				show_help
+				exit 1
+				;;
+			*) # Default case: If no more options then break out of the loop.
+				#if [ -n "$1" ]; then
+					container_image="$1"
+					chroot_directory="$2"
+					shift
+				#else
+					break
+				#fi
+				;;
+		esac
+	done
+}
 
 function show_help(){
 	cat << EOF
@@ -21,77 +96,50 @@ hello world
 EOF
 }
 
-while :; do
-	case $1 in
-		-h | --help)
-			# Call a "show_help" function to display a synopsis, then exit.
-			show_help
-			exit 0
-			;;
-		-v | --verbose)
-			verbose=1
-			#verbose_key="s
-			shift
-			;;
-		-V | --version)
-			printf "distrobox: %s\n" "${version}"
-			exit 0
-			;;
-		-i | --image)
-			if [ -n "$2" ]; then
-				container_image="$2"
-				shift
-				shift
-			fi
-			;;
-		-F | --flush) # function to then remove the image from the host
-			flush=1
-			shift
-			;;
-		-t | --target-directory)
-			if [ -n "$2" ]; then
-				chroot_directory="$2"
-				shift
-				shift
-			fi
-			;;
-		--) # End of all options.
-			shift
-			break
-			;;
-		-*) # Invalid options.
-			printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
-			show_help
-			exit 1
-			;;
-		*) # Default case: If no more options then break out of the loop.
-			# If we have a flagless option and container_name is not specified
-			# then let's accept argument as container_name
-			if [ -n "$1" ]; then
-				container_name="$1"
-				chroot_directory="$2"
-				shift
-			else
-				break
-			fi
-			;;
-	esac
-done
+function check_args(){
+	if [ -z ${container_image} ] || [ -z ${chroot_directory} ]; then
+		show_help
+		exit 1
+	fi
+}
 
-if [ "${verbose}" -ne 0 ]; then
-	set -o xtrace
-fi
+function init_verbose(){
+	if [ "${verbose}" -ne 0 ]; then
+		set -o xtrace
+	fi
+}
 
 
-# the program (aka the main function)
+function check_privileges() {
+	if [ "$EUID" -ne 0 ] && [ ${rootless} -eq 0 ]; then
+	echo "Please run as root or use --rootless option (not recommended)"
+  	exit 1;
+	fi
+}
 
-# test if directory exists
+function podman_main(){
+	
+#	podman save debian:unstable | tar -xpf - -O | tar -xpvf -
+	# check if image exists, if it does, dont flush
+	if [ $(podman image exists ${container_image}) ]; then
+		flush=0
+	fi
 
-echo "
+	if [ ! $(podman image exists ${container_image}) ]; then
+		podman pull ${container_image}
+	fi	
 
-if [ ! -d "$chroot_directory" ] || [ -z ${container_image} ] && [ -z ${chroot_directory} ] then
-	show_help	
-	exit 1;
-fi
+	## there should the the tar pipe 
 
-podman save ${container_image} | tar -xf "*.tar" -C ${chroot_directory}
+	echo $flush # debug
+
+	if [ ${flush} -eq 1 ]; then
+		echo "removing the image" # debug (maybe output, idk)
+		podman image rm ${container_image}
+	fi
+
+
+
+}
+
+main "$@" # bash moment
